#!/usr/bin/env python

import sys

from rqt_rosbag_control.rqt_rosbag_control import RosbagControlPlugin
from rqt_gui.main import Main

plugin = 'rqt_rosbag_control'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
